version: 2
jobs:
  build:
    working_directory: ~/fern
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: fern-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: fern-{{ checksum "project.clj" }}
      - run: lein do test, jar
      - store_artifacts:
          path: target/jar/fern.jar
